TARGETS = cpuclock cpuclock2 cpuclock3

CFLAGS = -std=gnu99 -g -Wall 
LDFLAGS = -lrt -lpthread

all: $(TARGETS)
clean:
	rm $(TARGETS)

cpuclock: cpuclock.c
cpuclock2: cpuclock2.c
cpuclock3: cpuclock3.c